name: print_app
description: A new Flutter project called Print App.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  pine: ^1.0.4
  flutter_bloc: ^9.1.1
  provider: ^6.1.5
  json_annotation: ^4.9.0
  uuid: ^4.5.1
  auto_route: ^10.1.0+1
  intl: ^0.20.2
  flutter_blue_plus: ^1.35.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.5.2
  auto_route_generator: ^10.0.0


flutter:
  uses-material-design: true
  assets:
    - lib/other/media/images/

